export const starshipTestFlight4Events = {
  Starship: [
    {
      time: '0:00',
      timestamp: 0,
      label: 'Launch',
      caption: 'Starbase TX',
      lat: 25.9973,
      lon: -97.1573,
      heading: 95,
      altitude: 0,
      speed: 0,
    },
    {
      time: '08:09',
      timestamp: 489,
      label: 'Main Engine Cutoff',
      caption: 'Starship',
      lat: 25.2,
      lon: -90.5,
      altitude: 147,
      speed: 24992,
    },
    {
      time: '15:00',
      timestamp: 900,
      label: '',
      caption: 'Starship',
      lat: 10.0,
      lon: -40.0,
      altitude: 190,
      speed: 26325,
    },
    {
      time: '30:00',
      timestamp: 1800,
      label: '',
      caption: 'Starship',
      lat: -20,
      lon: 40.0,
      altitude: 203,
      speed: 26263,
    },
    {
      time: '44:00',
      timestamp: 2640,
      label: 'Approx. Plasma Buildup Start',
      caption: 'Starship',
      lat: -19.0,
      lon: 80.0,
      altitude: 151,
      speed: 26498,
    },
    {
      time: '1:06:00',
      timestamp: 3960,
      label: 'Water Landing',
      caption: 'Starship',
      lat: -12.0,
      lon: 105.0,
      altitude: 0,
      speed: 0,
    },
  ],
  Booster: [
    {
      time: '0:00',
      timestamp: 0,
      label: 'Launch',
      caption: 'Starbase TX',
      lat: 25.9973,
      lon: -97.1573,
      heading: 95,
      altitude: 0,
      speed: 0,
    },
    {
      time: '00:59',
      timestamp: 59,
      label: 'Max Q',
      lat: 24.5,
      lon: -95.5,
      altitude: 7,
      speed: 1002,
    },
    {
      time: '02:49',
      timestamp: 169,
      label: 'Booster Engine Cutoff',
      lat: 23.0,
      lon: -93.0,
      altitude: 69,
      speed: 5528,
    },
    {
      time: '02:57',
      timestamp: 177,
      label: 'Stage Separation',
      caption: 'Begin Boostback Burn',
      lat: 22.9,
      lon: -92.8,
      altitude: 75,
      speed: 5440,
    },
    {
      time: '03:35',
      timestamp: 215,
      label: 'End Boostback Burn',
      caption: 'Booster',
      lat: 23.0,
      lon: -93.0,
      altitude: 106,
      speed: 1257,
    },
    {
      time: '06:13',
      timestamp: 373,
      label: 'Descent',
      caption: 'Booster',
      lat: 24.5,
      lon: -95.5,
      altitude: 52,
      speed: 3848,
    },
    {
      time: '07:10',
      timestamp: 430,
      label: 'Landing Burn',
      caption: 'Booster',
      lat: 24.6,
      lon: -95.6,
      altitude: 0.7,
      speed: 593,
    },
    {
      time: '07:31',
      timestamp: 451,
      label: 'Water Landing',
      caption: 'Booster, Gulf of MX',
      lat: 24.6,
      lon: -95.6,
      altitude: 0,
      speed: 0,
    },
    {
      time: '08:09',
      timestamp: 489,
      label: 'Main Engine Cutoff',
      caption: 'Starship',
      lat: 25.2,
      lon: -90.5,
      altitude: 147,
      speed: 24992,
    },
    {
      time: '08:40',
      timestamp: 520,
      label: 'Inner Engine Cutoff',
      caption: 'Starship',
      lat: 21.5,
      lon: -88.0,
      altitude: 151,
      speed: 26498,
    },
    {
      time: '56:00',
      timestamp: 3360,
      label: 'Over Indian Ocean',
      caption: 'Starship',
      lat: -10.0,
      lon: 100.0,
      altitude: 58,
      speed: 17808,
    },
    {
      time: '1:05:42',
      timestamp: 3942,
      label: 'Landing Burn',
      caption: 'Starship',
      lat: -12.0,
      lon: 105.0,
      altitude: 0.7,
      speed: 284,
    },
  ],
};

export const falcon9EstimatedEvents = [
  {
    time: 0,
    label: 'Launch',
    caption: 'Cape Canaveral',
    lat: 28.5623,
    lon: -80.5774,
    altitude: 0,
  },
  {
    time: 60,
    label: 'Max-Q',
    caption: 'Over the Atlantic Ocean',
    lat: 28.6,
    lon: -80.4,
    altitude: 15,
  },
  {
    time: 150,
    label: 'Main Engine Cutoff (MECO)',
    caption: 'Over the Atlantic Ocean',
    lat: 28.7,
    lon: -79.6,
    altitude: 70,
  },
  {
    time: 154,
    label: 'Stage Separation',
    caption: 'Over the Atlantic Ocean',
    lat: 28.7,
    lon: -79.6,
    altitude: 70,
  },
  {
    time: 156,
    label: 'Second Stage Ignition (SES-1)',
    caption: 'Over the Atlantic Ocean',
    lat: 28.7,
    lon: -79.6,
    altitude: 80,
  },
  {
    time: 180,
    label: 'Fairing Separation',
    caption: 'Over the Atlantic Ocean',
    lat: 28.8,
    lon: -79.7,
    altitude: 100,
  },
  {
    time: 480,
    label: 'First Stage Entry Burn',
    caption: 'Over the Atlantic Ocean',
    lat: 29.0,
    lon: -75.0,
    altitude: 60,
  },
  {
    time: 510,
    label: 'First Stage Landing Burn',
    caption: 'Over the Atlantic Ocean',
    lat: 29.1,
    lon: -74.1,
    altitude: 20,
  },
  {
    time: 530,
    label: 'First Stage Landing',
    caption: 'Drone Ship',
    lat: 29.2,
    lon: -73.2,
    altitude: 0,
  },
  {
    time: 540,
    label: 'Second Stage Cutoff (SECO-1)',
    caption: 'Over the Atlantic Ocean',
    lat: 28.5,
    lon: -60.0,
    altitude: 200,
  },
  {
    time: 2700,
    label: 'Second Stage Ignition (SES-2)',
    caption: 'Over the Atlantic Ocean',
    lat: 30.0,
    lon: 0.0,
    altitude: 200,
  },
  {
    time: 2730,
    label: 'Second Stage Cutoff (SECO-2)',
    caption: 'Over the Atlantic Ocean',
    lat: 30.0,
    lon: 0.0,
    altitude: 300,
  },
  {
    time: 3600,
    label: 'Payload Deployment',
    caption: 'Over the Atlantic Ocean',
    lat: 30.5,
    lon: 0.5,
    altitude: 300,
  },
  {
    time: 3900,
    label: 'Second Stage Deorbit Burn',
    caption: 'Over the Atlantic Ocean',
    lat: 31.0,
    lon: 1.0,
    altitude: 300,
  },
  {
    time: 5400,
    label: 'Second Stage Reentry and Landing',
    caption: 'Over the Atlantic Ocean',
    lat: 31.5,
    lon: 1.5,
    altitude: 0,
  },
  {
    time: 6000,
    label: 'Post-deployment: Satellites Drift and SpaceX Checks',
    caption: 'Varies depending on the mission profile',
    lat: 32.0,
    lon: 2.0,
    altitude: 350,
  },
];
export const earthRadius = 1;
